#+OPTIONS: H:1
#+TODO: TODO(t) IN-PROGRESS(i) TESTING(t) WISHLIST(s) WAITING(w) DONE(d)
#+TAGS: ADMIN_PANEL(a) FEATURE(f) BUG(b) DOCUMENTATION(d) RESEARCH(r) TEMPLATE(t) REFACTOR(c)


* WP Rets
  A Wordpress plugin for integrating the Reichert Brothers RetsD API into your
  wordpress site.

** Installation
   Clone this repo in any Wordpress site's =wp-content/plugins/= directory
   and activate it through the admin panel.

** Features and Usage
*** Admin Settings
    Set your api credentials in the admin panel (=Options -> RetsD=)
    - api name
    - api key

*** Displaying Properties
    - [retsd_residential]
      View all residential listings
    - [restd_openhouses]
      View all open houses.


* ============================================================================ *


* TODO *

*** TODO Build out search form and make it send a request           :FEATURE:
*** TODO Add options for 'registered' search fields     :ADMIN_PANEL:FEATURE:
    The admin should be able to choose which fields the user is able to search with.
    It could be any easy way to make construcable and custom search forms for any page.
