#+OPTIONS: H:1
#+TODO: TODO(t) IN-PROGRESS(i) TESTING(t) WISHLIST(s) WAITING(w) DONE(d)
#+TAGS: FEATURE(f) BUG(b) DOCUMENTATION(d) RESEARCH(r) TEMPLATE(t) REFACTOR(c)


* WP Rets
  A Wordpress plugin for integrating the Reichert Brothers RetsD API into your
  wordpress site.

** Installation
   Clone this repo in any Wordpress site's =wp-content/plugins/= directory
   and activate it through the admin panel.

** Features and Usage
*** Admin Settings
    Set your api credentials in the admin panel (=Options -> RetsD=)
    - api name
    - api key

*** Displaying Properties
    - [retsd_residential]
      View all residential listings
    - [restd_openhouses]
      View all open houses.


* ============================================================================ *


* TODO *
  |FEATURE|BUG|DOCUMENTATION|RESEARCH|TEMPLATE|REFACTOR|

*** TODO Create links to individual property pages         :FEATURE:RESEARCH:
*** TODO Build out search form and make it send a request       :FEATURE:BUG:
*** TODO Add options for 'registered' search fields                 :FEATURE:
    The admin should be able to choose which fields the user is able to search with.
    It could be any easy way to make construcable and custom search forms for any page.
*** TODO Ability to create custom searches                          :FEATURE:
    The admin can basically create a shortcode that stores a list of search
    parameters. Then they can embed the results of specific searches on any page
