#+OPTIONS: H:1
#+TODO: TODO(t) IN-PROGRESS(i) TESTING(t) WISHLIST(s) WAITING(w) DONE(d)
#+TAGS: FEATURE(f) BUG(b) DOCUMENTATION(d) RESEARCH(r) TEMPLATE(t) REFACTOR(c)


* WP Rets
  A Wordpress plugin for integrating the Reichert Brothers RetsD API into your
  wordpress site.

** Installation
   Clone this repo in any Wordpress site's =wp-content/plugins/= directory
   and activate it through the admin panel.

** Features and Usage
*** Admin Settings
    Set your api credentials in the admin panel (=Options -> RetsD=)
    - api name
    - api key

*** Displaying Properties
    - [retsd_residential]
      View all residential listings
    - [restd_openhouses]
      View all open houses.


* ============================================================================ *


* TODO *
  |FEATURE|BUG|DOCUMENTATION|RESEARCH|TEMPLATE|REFACTOR|

*** TODO Create links to individual property pages         :FEATURE:RESEARCH:
*** TODO Build out search form and make it send a request       :FEATURE:BUG:
*** TODO Add options for 'registered' search fields                 :FEATURE:
    The admin should be able to choose which fields the user is able to search with.
    It could be any easy way to make construcable and custom search forms for any page.
*** TODO Ability to create custom searches                          :FEATURE:
    The admin can basically create a shortcode that stores a list of search
    parameters. Then they can embed the results of specific searches on any page
*** TODO Provide a Search Form Widget to be put anywhere
*** TODO 

The plugin should have the following features:
- The ability to plug a short code in anywhere that will yeild the result of
  a search. Whether that's one listing or many, but these shortcodes are not
  searches, just results
- The ability for the admin to specify which page is the main search listings
  page. They'll do this by picking SimpleRets Search Page template on the
  'Create a New Page' page. This page will by default have a search form on it
  that can be used to search all properties.
- Add two widgets. One is a search form that, when searched, redirects to the
  specified 'search listings page' and another widget that takes one of the
  shortcodes mentioed above and creates a property(ies) widget.
- Ability to set css for all of the above, with a couple of default layouts.
