* SimplyRETS WP [[https://travis-ci.org/SimplyRETS/simplyretswp.svg?branch=master]]

  This is the official repository of the SimplyRETS Wordpress plugin
  client.

  SimplyRETS enables you to embed *your* live real estate listings
  directly on your site simply and easily.

  The Wordpress plugin provides you a simply way to connect to your
  SimplyRETS account and start showing your real estate listings
  directly on your Wordpress site. It provides Wordpress standard
  custom post types, sidebard and footer widgets, shortcodes, and
  more.

  The plugin requires an active plan with SimplyRETS to enable /your/
  listings, but we also provide a demo test account with real listings
  that you can use to test out the plugin and make sure it does what
  you need it to.

  For any support related issues, you can:
  1) View the documentation at http://docs.simplyrets.com
  2) Submit an issue on the official SimplyRETS WP github mirror: http://github.com/rbros/simplyretswp/issues
  3) Send us a message via our website contact form at http://simplyrets.com/#home-contact
  4) Send an email to [[mailto:support@simplyrets.com]]

  *If you have an active SimplyRETS account, you can also submit a
  support request via your [[https://simplyrets.com/account][SimplyRETS Account Panel]].*

  /Pull requests are welcomed!/

** Installation

*** Install from .zip file
    - Download the `.zip` file from [[https://github.com/rbros/simplyretswp/releases][the releases page]].
    - In your Wordpress dashboard, go to 'Plugins' -> 'Add New'.
      Choose 'Upload a New Plugin' and upload the `.zip` file.
    - Activate it through the =Plugins -> Installed plugins= page of your Wordpress dashboard.

*** Extract from .zip file
    - Download the `.zip` file from [[https://github.com/rbros/simplyretswp/releases][the releases page]].
    - Unzip the file in your Wordpress site's =wp-content/plugins/= directory.
    - Activate it through the =Plugins -> Installed plugins= page of your Wordpress dashboard.

*** Activating
    Once the plugin is installed via one of the methods above, you
    need to active it using a set of API credentials. If you want to
    use the test data, you can use the credentials provided on the
    =Settings -> SimplyRETS= page of your dashboard. Enther them and
    activate! If you have an account with SimplyRETS, enter /your/
    credentials on that page instead.

** Getting Started
*** Creating SimplyRETS Pages
    A new page type is created called SimplyRETS Pages. You can create
    new SimplyRETS pages to show results from listings searches.

    By default, a new page will show all listings. You can add 'filters'
    to the page to create more advanced pages that only show certain
    listings (ie, only residential listings for sale that are more that
    $500,000). These are basically just pages that you an have content
    on and embed listings into.

**** Filters
     1) Minimum Price
     2) Maximum Price
     3) Minimum Bedrooms
     4) Maximum Bedrooms
     5) Listing Agent Id

**** Page Templates and Layout
     Most themes come with a few different options for each page's
     layout. Most common are "Right Sidebar", "Full-Width", etc. SimplyRETS
     allows you to use these same templates on SimplyRETS Pages.

     *Results Pages:* On SimplyRETS Pages, you can choose the theme
     template to use in the right sidebar just like any other page. This
     allows the user to use pages with a sidebar, or other layouts their
     theme may offer.

     *Single Listing Details Pages:* Since single listing pages are
     created dynamically, we don't have access to choose the template
     like the other pages. Instead, you set this in the Settings
     page. The same options apply, like sidebar and full-width. This
     setting will take effect on all single listing details pages.

*** ShortCodes
    Shortcodes are provided to add additionally functionality or information
    to any of your posts or pages.
**** Search Form Shortcode: [sr_search_form]
     Embed this shortcode on any page or post in your Wordpress site to
     provide a SimplyRETS search form that will search all of your
     listings. The best use of this is to add it to the top of one of
     the SimplyRETS Pages in order to make it a fully featured search
     and results page.

**** Residential Shortcode: [sr_residential]
     The sr_residential shortcode allows you to embed one or more
     listings into any page or post on your site. By default, it will
     show 25 results from a search for all residential properties. Each
     result from this shortcode will show the main photo and a few
     details with a link to the listing's single page.
***** Parameters
      You can customise the listings that show up with this short code
      by using the following parameters.
      1) MLS Id (mlsid):
         Use this parameter to insert a /specific/ listing by MLS Id.
         Using this parameter will override any other parameters
         within the same shortcode.
         Example: [sr_residential mlsid="123456"]

*** Widgets
    SimplyRETS provides you with widgets you can use in your sidebar or footer
    just like any other widget on your site.

**** Featured Listing Widget
     Use the Listing Widget to embed a single RETS listing in your
     sidebar or elsewhere.
     It takes a title for the Widget area, and an MLS ID of the property
     that you want to show on that widget.

** Style Guide
   The SimplyRETS Wordpress styleguide provides an overview of the HTML
   and css classes and id's used to style the listings. To make customizations
   to your site, use this style guide to easily find which elements to style.

   You can view the style guide in [[https://docs.simplyrets.com][the SimplyRETS documentation]]

   To generate the the style guide:
   - Install StyleDocco via npm:
   #+BEGIN_SRC bash
   $ npm install -g styledocco
   #+END_SRC
   - And run it from the top level of this repo:
   #+BEGIN_SRC bash
   $ styledocco -n "SimplyRETS Style Guide" css/simply-rets-client.css
   #+END_SRC

   Note: we only need the simply-rets-client.html file

** License
   *This software is licensed under the GNU General Publice License Version 3.0*

   Copyright (C) 2014-2015 SimplyRETS
   Authored by: Cody Reichert

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   in a LICENSE file along with this program.  If not, see
   [[http://www.gnu.org/licenses/]]
