* WP Rets
  The official repository for the Simply Rets Wordpress plugin.

  Simply Rets enables you to embed *your* real estate listings directly
  on your site, with minimal setup and hassle.

  This the official Wordpress Plugin for Simply Rets. It connects Wordpress sites
  to your Simply Rets account and feeds your properties directly to the Wordpress
  pages you choose. Read on to find out more about how it works.

** Installation
   1) Clone this repo in any Wordpress site's =wp-content/plugins/= directory
   and activate it through Plugins page of the admin panel.
   2) Enter your Simply Rets API Credentials in the WP Admin Panel.
      (see *Admin Settings*)
      
      Note: the plugin also provides API credentials for demo listing data, so you can
      try it out on your Wordpress site. To get the credentials, install the plugin and
      look in the admin panel.
      

** Admin Settings
    Set your API credentials in the admin panel (=Options -> RetsD=)
    - API name
    - API key


** Getting Started 

*** Creating Simple Rets Pages
    A new page type is created called Simple Rets Pages. You can create
    new Simple Rets pages to show results from listings searches.

    By default, a new page will show all listings. You can add 'filters'
    to the page to create more advanced pages that only show certain
    listings (ie, only residential listings for sale that are more that
    $500,000). These are basically just pages that you an have content
    on and embed listings into.
**** Filters
     1) Minimum Price
     2) Maximum Price
     3) Minimum Bedrooms
     4) Maximum Bedrooms
     5) Listing Agent Id


*** Page Templates and Layout
    Most themes come with a few different options for each page's
    layout. Most common are "Right Sidebar", "Full-Width", etc. Simple
    Rets allows you to use these same templates on Simple Rets Pages.

    *Results Pages:* On Simple Rets Pages, you can choose the theme
    template to use in the right sidebar just like any other page. This
    allows the user to use pages with a sidebar, or other layouts their
    theme may offer.

    *Single Listing Details Pages:* Since single listing pages are
    created dynamically, we don't have access to choose the template
    like the other pages. Instead, you set this in the Settings
    page. The same options apply, like sidebar and full-width. This
    setting will take effect on all single listing details pages.


*** ShortCodes
    Shortcodes are provided to add additionally functionality or information
    to any of your posts or pages.
**** Search Form Shortcode: [sr_search_form]
    Embed this shortcode on any page or post in your Wordpress site to
    provide a Simply Rets search form that will search all of your
    listings. The best use of this is to add it to the top of one of
    the Simple Rets Pages in order to make it a fully featured search
    and results page.

**** Residential Shortcode: [sr_residential]
    The sr_residential shortcode allows you to embed one or more
    listings into any page or post on your site. By default, it will
    show 25 results from a search for all residential properties. Each
    result from this shortcode will show the main photo and a few
    details with a link to the listing's single page.
***** Parameters
     You can customise the listings that show up with this short code
     by using the following parameters.
     1) MLS Id (mlsid):
        Use this parameter to insert a /specific/ listing by MLS Id.
        Using this parameter will override any other parameters
        within the same shortcode.
        Example: [sr_residential mlsid="123456"]


*** /COMING SOON/ Widgets
    Simple Rets provides two widgets you can use just like any other widget
    on your site.

    *Search Widget:* Use the Search Widget to embed a small search form in
    your sidebar or elsewhere.

    *Listing Widget:* Use the Listing Widget to embed a single Rets listing
    in your sidebar or elsewhere.


